name: Build for Windows
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: git mingw-w64-i686-toolchain mingw-w64-i686-llvm
      - name: CI-Build
        run: |
          mingw32-make
